// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ShortenService is an autogenerated mock type for the ShortenService type
type ShortenService struct {
	mock.Mock
}

// ShortenURL provides a mock function with given fields: ctx, url, exp
func (_m *ShortenService) ShortenURL(ctx context.Context, url string, exp time.Duration) (string, error) {
	ret := _m.Called(ctx, url, exp)

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, url, exp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, url, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, url, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortenService creates a new instance of ShortenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenService {
	mock := &ShortenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
